
USE ROLE SYSADMIN;
USE WAREHOUSE MYSNOWWAREHOUSE;

USE DATABASE MYSNOWDATABASE;

USE SCHEMA MYSNOWSCHEMA;

Alter table EMPLOYEE_PROFILE ADD Column office_phone_num varchar;

USE ROLE SECURITYADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA MYSNOWDATABASE.MYSNOWSCHEMA TO EMPLOYEE_READ_ROLE ;